Removed console warnings for FeaturedActivity
ThatConference/that.us pull request #1093
Opened 2021-11-22 22:15 UTC by ategen3rt

Used lodash's pick to get the 4 fields that FeaturedActivity wants to make the console warnings go away

2021-11-25 15:19 UTC, csell5 approved these changes
Oh shit.. that's a sweet little utility.

2021-11-25 15:27 UTC, csell5 requested changes
Build failed.

```
SyntaxError: Named export 'pick' not found. The requested module 'lodash' is a CommonJS module, which may not support all module.exports as named exports.
```

you had load lodash differently because it's a cjs library.

import lodash from 'lodash';
const { pick } = lodash;

2021-12-03 22:01 UTC, ategen3rt commented
Updated to use the new speakers field under the event

2021-12-08 23:36 UTC, csell5 approved these changes

2021-12-08 23:36 UTC, merged