refactor: add missing trainingSlash entries for svelte v1
ThatConference/that.us pull request #1374
Opened 2023-04-19 23:28 UTC by brettski

v3.2.2
refactor: add missing trainingSlash entries for svelte v1
versioning set using package.json

that.us now reads version from `package.json` and uses that version for sentry maps.

2023-04-19 23:39 UTC, csell5 requested changes
I believe then gfetch has to have the trailing slash added back to the urls as I took them off.

2023-04-19 23:41 UTC, brettski commented
> I believe then gfetch has to have the trailing slash added back to the urls as I took them off.

This is currently running in the `feature` branch. Which calls use gfetch, proxy ones only, right?

2023-04-20 00:26 UTC, brettski commented
Added trailing slashes back to gfetch.js. This is how they currently are in thatconference.com as well.

2023-04-20 00:27 UTC, csell5 approved these changes

2023-04-20 00:40 UTC, csell5 approved these changes

2023-04-20 00:44 UTC, merged