Fixing Tidio Problem
ThatConference/that.us pull request #391
Opened 2020-10-04 23:04 UTC by Yassine-Latreche

Hi,
I fixed the problem you had with the Tidio Chat and the Error Messege as you requested in #385 .

2020-10-05 12:42 UTC, csell5 requested changes

2020-10-05 12:42 UTC, csell5 commented on src/components/notifications/Error.svelte
> +    style="z-index : 10;"
Since we're already using Tailwind, you can drop the style here and just add a class of z-10

2020-10-05 12:42 UTC, csell5 commented on src/App.svelte
> +  <script
We're not going to take in jquery. But in Svelte we can just do that in onLoad and call window directly.

2020-10-05 17:07 UTC, Yassine-Latreche commented on src/components/notifications/Error.svelte
> +    style="z-index : 10;"
Hi,
I have never used Tailwind, so it's new thing for me.
It's updated now.

2020-10-05 17:13 UTC, Yassine-Latreche commented on src/App.svelte
> +  <script
The problem is that the `iframe`is generated by the Tidio script, that's why i think we can't use Svelte.

2020-10-06 13:13 UTC, csell5 commented on src/App.svelte
> +  <script
I'm sorry I said onLoad but I meant to say onMount.

2020-10-06 13:13 UTC, csell5 commented on src/App.svelte
> +  <script
I'll review here in a few.

2020-10-06 13:24 UTC, csell5 commented on src/App.svelte
> +        document.getElementById('tidio-chat-iframe').style.zIndex = '2';
I know I said onLoad but I meant onMount which is already above.. So you just literally take this one line and drop that in that function and it should be rocking.

2020-10-06 13:25 UTC, csell5 requested changes

2020-10-06 13:25 UTC, csell5 commented on src/App.svelte
> +        document.getElementById('tidio-chat-iframe').style.zIndex = '2';
again sorry about miss leading ya there.

2020-10-06 16:23 UTC, Yassine-Latreche commented on src/App.svelte
> +  <script
Done.

2020-10-06 16:24 UTC, Yassine-Latreche commented on src/App.svelte
> +        document.getElementById('tidio-chat-iframe').style.zIndex = '2';
It's Okay
I just fixed it as you asked for

2020-10-06 17:59 UTC, csell5 commented
@all-contributors please add @Yassine-Latreche for code.

2020-10-06 18:07 UTC, csell5 approved these changes

2020-10-06 18:07 UTC, csell5 commented
@Yassine-Latreche Thank You!

2020-10-06 18:07 UTC, merged