Issue 531, fixing weird sticky date behavior
ThatConference/that.us pull request #561
Opened 2021-01-25 22:13 UTC by asharonbaltazar

Dates in the Activities page now scroll as expected. 

Something needs to be done about the filter when the viewport is of mobile width. See:

![image](https://user-images.githubusercontent.com/58940073/105772691-30fab780-5f28-11eb-8c8d-6aad9fec58aa.png)

2021-01-27 18:20 UTC, csell5 requested changes
FYI, I did update the branch to rebase on top of your other changes.

There are a few changes needed here.

First things are now cutting off the top of the items in the grid
![image](https://user-images.githubusercontent.com/772569/106034911-1ac03900-6099-11eb-83f1-974ab6ae2497.png)

I think the spirt of the issue wasn't so much about the placement of the header, but it was the placement of the header when it was the last item for that slot. thus you end up like this:

![image](https://user-images.githubusercontent.com/772569/106035114-53601280-6099-11eb-8b2d-0d3c8783b757.png)

It would be a cleaner approach if that last item in that slot could put the header out of the way vs, the next header. Clearly not designed that way, and this isn't a super critical issue by any means.  

The problem I see with your changes.
* the time is is never vertically aligned which is hard to track
* Mobile layout is different than desktop so it's confusing.
* The problem with where the time is at, when a slot is "full" we're three items wide, which means that time is now fighting in the middle item.
* and in the end we still didn't solve the true issue

![image](https://user-images.githubusercontent.com/772569/106035465-c7021f80-6099-11eb-85fa-78218237fbe2.png)

Ironically you could make an argument that in desktop mode, it just just pop out to the left alongside that main content grid. I never looked into that.

2021-01-27 18:29 UTC, asharonbaltazar commented
I must've misunderstood the issue then. 

I'll take a look later today.

2021-01-27 18:33 UTC, csell5 commented
I know all the issues don't have the best documentation around them, so feel to ask any leading questions and I'm happy to add as much context/direction as possible. We can always setup a activity on that.us too

2021-01-27 18:35 UTC, asharonbaltazar commented
Yeah, thanks for clarification. I don't want to seem like I didn't understand anything.

2021-01-27 18:56 UTC, csell5 commented
oh I didn't take it that way. I'm grateful for the help and anything I can do to help just let me know.

2021-01-28 00:15 UTC, asharonbaltazar commented
![image](https://user-images.githubusercontent.com/58940073/106071205-88855880-60cb-11eb-9bdf-29464c9ce95b.png)

What can we do about this? This isn't a new bug; it's been always there. Seems like the `z-index` needs to be upped on the chat bubble.

2021-01-28 15:42 UTC, csell5 commented
ok, a little back story on some tech debt here. 

We had reset the z-index of the chat bubble as it was conflicting with the warning and error boxes that pop up at the bottom. So we pushed it down.

https://github.com/ThatConference/that.us/blob/master/src/App.svelte#L35-L39

those modals could be rethought a bit but a quick fix for now I think is to just reworking the z-index of those three items so they layer right. 

FWIW The only reason there is a background on that header, was to hide the cards as they scrolled under.

2021-01-28 16:22 UTC, asharonbaltazar commented
Other than the `z-index`, is everything okay?

2021-01-28 16:28 UTC, csell5 commented
yea but can we make one last change? I know why you removed the padding at the top so you couldn't see the gap, that's cool.

Can we add some spacing to get the top of the date to align with the top of the search box?

![image](https://user-images.githubusercontent.com/772569/106167976-63d4c380-6153-11eb-941c-da07c222a690.png)

2021-01-28 16:32 UTC, asharonbaltazar commented
Seems like it's not just the dates...

![image](https://user-images.githubusercontent.com/58940073/106168617-1c9b0280-6154-11eb-88ce-0ed635a4e5c2.png)

2021-01-28 17:36 UTC, csell5 commented
Looks like the sticky header isn't working anymore.

2021-01-28 17:55 UTC, asharonbaltazar commented
I'm sorry, but what header? Everything seems to be working for me unless overlooked something...

2021-01-28 19:42 UTC, csell5 commented
After looking further. It appears to just be broken in Safari. I know you're on windows so maybe we just file a new issue related to just that and link it back to this pr.

2021-01-29 15:21 UTC, asharonbaltazar commented
What should be done regarding this?

2021-01-29 15:35 UTC, csell5 commented
I'm going to take a closer look here today and see what I can suss out. might be something simple we can add into this.

2021-01-29 19:19 UTC, csell5 commented on src/components/activities/List.svelte
> +        tracking-tight text-thatBlue-800 sm:text-4xl sm:leading-10 pt-4 pb-10 inline-block"
inline-block is causing the issues in safari with sticky not sticking

2021-01-29 19:19 UTC, csell5 commented on src/components/activities/List.svelte
> +            tracking-tight text-thatOrange-400 sm:text-4xl sm:leading-10 inline-block"
inline-block is causing the issues in safari with sticky not sticking

2021-01-29 19:20 UTC, csell5 requested changes
I'm not sure why `inline-block` is causing sticky to not work in Safari but removing it fixes that problem. It's worth looking into a bit more.

2021-01-29 19:22 UTC, asharonbaltazar commented
Please tell me what's happening on your end.

[Stackoverflow issue](https://stackoverflow.com/questions/38955362/displayinline-block-not-working-on-safari)

2021-01-29 19:30 UTC, csell5 commented
![Kapture 2021-01-29 at 13 29 43](https://user-images.githubusercontent.com/772569/106318822-17ae7f80-6236-11eb-8393-26db8eb3857c.gif)

2021-01-29 19:31 UTC, asharonbaltazar commented
Oh, I meant more like what the dev tools are showing. I linked an issue from StackOverflow. Apparently, it's not just us.

2021-01-29 19:36 UTC, asharonbaltazar commented
Also noticed that when there is more than one event, the issue crops up back again. 

![image](https://user-images.githubusercontent.com/58940073/106319349-ebdfc980-6236-11eb-8b45-b81162accc6a.png)

2021-01-29 19:40 UTC, csell5 commented
I'm not really sure why it doesn't work in Safari. They look exactly the same. Brave left, Safari Right.

![image](https://user-images.githubusercontent.com/772569/106319710-77f1f100-6237-11eb-82c9-3346de7282cf.png)

2021-01-29 19:45 UTC, asharonbaltazar commented
Can you try adding `position: -webkit-sticky;`, please?

2021-01-29 19:53 UTC, csell5 commented
that didn't work. best I can tell. the inline-block is throwing off the height for sticky, so it doesn't know where to stick. Just a guess at the moment.

2021-01-31 01:39 UTC, asharonbaltazar commented
It might be a little unorthodox but simply explained, the `div` and header blocks have `block` applied to them by default. So if we change that `div` to something like `span`, the problem ceases to exist.

2021-02-01 15:01 UTC, csell5 commented
but you removed the inline-block also.

2021-02-01 15:03 UTC, asharonbaltazar commented
I eliminated the need for it. Does it work for you?

2021-02-01 15:05 UTC, csell5 commented
ah, I'm following. I gotcha. yea we can roll with it.

2021-02-01 15:05 UTC, csell5 commented
fixes #531

2021-02-01 15:05 UTC, merged

2021-02-01 15:09 UTC, csell5 commented
I swear to you, I had just tested this in safari and it was working.. Now after the deployment it's not and it's not here either.

2021-02-01 15:10 UTC, asharonbaltazar commented
What in the world? Are the changes live?

2021-02-01 15:12 UTC, csell5 commented
yea. when we merge into the mainline it deploys to production. It must be the monday crazy.. Let's just create a new issue for it and then link it back to this one.

2021-02-01 15:12 UTC, asharonbaltazar commented
Also ![mobile](https://user-images.githubusercontent.com/58940073/106477188-7f024480-646d-11eb-853e-4515c937d763.png) needs some tweaking. It's working for me, but it's a bit messed up.

2021-02-01 15:13 UTC, csell5 commented
yea.. we should just shrink the font on smaller devices

2021-02-01 15:13 UTC, csell5 commented
and the search box, has and is janky on mobile too.

2021-02-01 15:20 UTC, asharonbaltazar commented
Yeah, it doesn't work for me either. I'm not near a computer now, but is it possible my changes somehow got messed up with all the commits and rebasing? 

What's the group's slack? Maybe we should take these conversations there.

2021-02-01 15:50 UTC, csell5 commented
could be, not sure to be honest.

thatslack.thatconference.com