Issue 565
ThatConference/that.us pull request #574
Opened 2021-02-08 17:47 UTC by asharonbaltazar

**Problem addressed**: 

Dates were squished and the filter was unusable due to screen restraints. 

**Problem fixed:** 

- Hid `input` on smaller screens. 
- Tweaked `h2`s sizes across all screens. 

**Problem hopefully fixed**:

Headers should now sticky on Safari.

2021-02-08 19:03 UTC, csell5 commented
@asharonbaltazar looks like you have some conflicts here.

2021-02-08 21:29 UTC, asharonbaltazar commented
Something's broken

2021-02-09 13:59 UTC, asharonbaltazar commented
Hold on. Don't merge this yet. I want to make one last change.

2021-02-09 18:29 UTC, csell5 requested changes
Take another look through this, looks like you're removing a few things you didn't mean too.

2021-02-09 18:29 UTC, csell5 commented on src/components/activities/List.svelte
> -  {:else}
I don't think you meant to remove this.. Maybe double check this pr.

2021-02-09 18:29 UTC, csell5 commented
@asharonbaltazar mind you, I did pull this branch up to latest on master.

2021-02-09 20:44 UTC, asharonbaltazar commented
I think it's because of that.

2021-02-09 21:42 UTC, csell5 approved these changes

2021-02-09 21:43 UTC, merged

2021-02-09 21:44 UTC, csell5 commented
Closes #565