Extend session details
ThatConference/that.us pull request #772
Opened 2021-06-24 04:01 UTC by joshpierce

Closes #771

2021-06-24 14:59 UTC, csell5 commented
- [ ] On the session details we need to make the logo link back to the event of which it is.

2021-06-24 15:03 UTC, csell5 requested changes
This code looks great. see the other two comments I left about session details.

2021-06-25 00:06 UTC, joshpierce commented
Love the ideas, implemented and ready for your review.

2021-06-25 00:39 UTC, csell5 approved these changes

2021-06-25 00:39 UTC, merged