Added concept for "THAT Certified" sessions. Also fixed "phantom" sha…
ThatConference/that.us pull request #788
Opened 2021-06-27 18:00 UTC by joshpierce

Added a concept for "THAT Certified" sessions. This does take up slightly more vertical space, but also better highlights the speaker of each of the sessions IMO. With the talk of adding a "cozy" layout to this as well, this is probably okay.

## Before Change 
![image](https://user-images.githubusercontent.com/8643537/123554767-3e220980-d747-11eb-99b2-193976eadf73.png)

## After Change
![image](https://user-images.githubusercontent.com/8643537/123554787-58f47e00-d747-11eb-8134-536c381aaa36.png)

Also can always change the verbiage, not sure what your thoughts were here @csell5.

Snuck in a bit of code for a design thing that was bothering me in the sticky timeslot headers on the activity list.

## Before Change (Notice Shadows Outside Sticky Header)
![image](https://user-images.githubusercontent.com/8643537/123554715-e84d6180-d746-11eb-80c9-30460af7eae1.png)

## After Change
![image](https://user-images.githubusercontent.com/8643537/123554742-18950000-d747-11eb-9c2b-03c7a488cfe3.png)

2021-06-28 15:57 UTC, csell5 commented
So the correct term here would be `Camp Counselor`. I can't say I have any other options, it for sure works for now. We also need to make sure that get's listed on the session detail page.

The only other thing I could think of doing is something with their profile image. Right now we overlay a merit badge but everyone gets or has one of those. so it doesn't really stand out.

2021-06-29 05:40 UTC, joshpierce commented
Changed the terminology on the page to Counselor, also added to the header on detail page, and cleaned up a couple of weird tailwind things there.

2021-06-29 13:15 UTC, csell5 requested changes

2021-06-29 13:15 UTC, csell5 commented on src/components/activities/ActivityDetails.svelte
> +              {#if type === 'REGULAR' || type === 'WORKSHOP'}
This should really be if the type !== `OPEN_SPACE`

2021-06-29 13:15 UTC, csell5 commented on src/components/activities/Card.svelte
> +  {#if type === 'REGULAR' || type === 'WORKSHOP'}
Same here..

2021-06-29 17:22 UTC, joshpierce commented on src/components/activities/ActivityDetails.svelte
> +              {#if type === 'REGULAR' || type === 'WORKSHOP'}
Yeah this makes more sense :) Also removed the Camp Counselor designation from the That Conference user, since it didn't make as much sense.

2021-06-29 17:22 UTC, joshpierce commented on src/components/activities/Card.svelte
> +  {#if type === 'REGULAR' || type === 'WORKSHOP'}
Yeah this makes more sense :) Also removed the Camp Counselor designation from the That Conference user, since it didn't make as much sense.

2021-06-29 18:00 UTC, csell5 approved these changes

2021-06-29 18:15 UTC, merged